<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Ccbr' => '',
  'Ccbr Branch' => '',
  'Ccbr Branches' => '',
  'Ccbr Ccmp' => '',
  'Ccbr Hide' => '',
  'Ccbr Name' => '',
  'Ccbr Notes' => '',
  'CcbrBranch.ccbr_ccmp_id' => '',
  'CcbrBranch.ccbr_hide' => '',
  'CcbrBranch.ccbr_id' => '',
  'CcbrBranch.ccbr_name' => '',
  'CcbrBranch.ccbr_notes' => '',
  'CcbrBranch.ccrb_code' => '',
  'Ccgr' => '',
  'Ccgr Group' => '',
  'Ccgr Groups' => '',
  'Ccgr Hide' => '',
  'Ccgr Name' => '',
  'Ccgr Notes' => '',
  'CcgrGroup.ccgr_hide' => '',
  'CcgrGroup.ccgr_id' => '',
  'CcgrGroup.ccgr_name' => '',
  'CcgrGroup.ccgr_notes' => '',
  'Ccmp' => '',
  'Ccmp Ccnt' => '',
  'Ccmp Companies' => '',
  'Ccmp Company' => '',
  'Ccmp Description' => '',
  'Ccmp Name' => '',
  'Ccmp Official Address' => '',
  'Ccmp Registration Address' => '',
  'Ccmp Registrtion No' => '',
  'Ccmp Statuss' => '',
  'Ccmp Vat Registrtion No' => '',
  'CcmpCompanies' => '',
  'CcmpCompany.ccmp_ccnt_id' => '',
  'CcmpCompany.ccmp_description' => '',
  'CcmpCompany.ccmp_id' => '',
  'CcmpCompany.ccmp_name' => '',
  'CcmpCompany.ccmp_official_address' => '',
  'CcmpCompany.ccmp_registration_address' => '',
  'CcmpCompany.ccmp_registrtion_no' => '',
  'CcmpCompany.ccmp_statuss' => '',
  'CcmpCompany.ccmp_vat_registrtion_no' => '',
  'Ccnt' => '',
  'Ccnt Code' => '',
  'Ccnt Countries' => '',
  'Ccnt Country' => '',
  'Ccnt Name' => '',
  'CcntCountry.ccnt_code' => '',
  'CcntCountry.ccnt_id' => '',
  'CcntCountry.ccnt_name' => '',
  'Ccrb Code' => '',
  'Ccxg' => '',
  'Ccxg Ccgr' => '',
  'Ccxg Ccmp' => '',
  'Ccxg Company Xgroup' => '',
  'Ccxg Company Xgroups' => '',
  'CcxgCompanyXGroup.ccxg_ccgr_id' => '',
  'CcxgCompanyXGroup.ccxg_ccmp_id' => '',
  'CcxgCompanyXGroup.ccxg_id' => '',
  'CcxgCompanyXGroups' => '',
  'Company branches' => '',
  'Company groups' => '',
  'Main comapny data' => '',
   'Companies' => 'Компании',
   'Name' => 'Название', 
   'Country' => 'Страна',
   'Registration Nr' => 'Номер регистрации',
   'State' => 'Статус',
   'Registration Address' => 'Адрес', 
);
