<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Ccbr' => '',
  'Ccbr Branch' => '',
  'Ccbr Branches' => '',
  'Ccbr Ccmp' => '',
  'Ccbr Hide' => '',
  'Ccbr Name' => '',
  'Ccbr Notes' => '',
  'CcbrBranch.ccbr_ccmp_id' => '',
  'CcbrBranch.ccbr_hide' => '',
  'CcbrBranch.ccbr_id' => '',
  'CcbrBranch.ccbr_name' => '',
  'CcbrBranch.ccbr_notes' => '',
  'CcbrBranch.ccrb_code' => '',
  'Ccgr' => '',
  'Ccgr Group' => '',
  'Ccgr Groups' => '',
  'Ccgr Hide' => '',
  'Ccgr Name' => '',
  'Ccgr Notes' => '',
  'CcgrGroup.ccgr_hide' => '',
  'CcgrGroup.ccgr_id' => '',
  'CcgrGroup.ccgr_name' => '',
  'CcgrGroup.ccgr_notes' => '',
  'Ccmp' => '',
  'Ccmp Ccnt' => '',
  'Ccmp Companies' => '',
  'Ccmp Company' => '',
  'Description' => 'Описание',
  'Office address' => 'Адрес офиса',
  'Legal address' => 'Юридический адрес',  
  'Legal address city' => 'Юридический адрес Город', 
  'Legal address Zip code' => 'Юридический адрес Почтовый индекс' ,
  'Ccmp Registration Address' => '',
  'Registration No' => 'Регистрационный номер',
  'Vat Registrtion No' => 'Регистрационный номер НДС',
  'Office City' => 'Офис Город',
  'Office email'  => 'E-mail',
  'Office phone' => 'Телефон',
  'Office Zip code' => 'Почтовый индекс',
  'Company branches' => 'филиалы',
  'Company groups' => 'группы',
  'Company managers' => 'менеджеры'  ,
  'Main comapny data' => 'основные данные',
  'Custom data' => 'пользовательские данные' ,
   'Companies' => 'Компании',
   'Name' => 'Название', 
   'Country' => 'Страна',
   'City' => 'Город',
   'Registration Nr' => 'Номер регистрации',
   'State' => 'Статус',
   'Registration Address' => 'Адрес', 
   'Trucks' => 'Грузовики',
   'Company data' => 'Данные компании'
);
