<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add' => 'добавлять',
  'Create' => 'создавать',
  'Empty' => 'Пустой',
  'Export' => 'экспорт',
  'Invalid request. Please do not repeat this request again.' => 'Неверный запрос. Пожалуйста, не повторяйте этот запрос снова.',
  'The requested page does not exist.' => 'Запрошенная страница не существует.',
  'New' => 'Создать',
  'Cancel' => 'Отменить',
  'Data' => 'Данные',
  'Delete' => 'Удалить',
  'Do you want to delete this item?' => 'Удалить?',
  'Fields with <span class="required">*</span> are required.' => '<span class="required">*</span> Обязательны',
  'List' => 'Список',
  'Manage' => 'Управлать',
  'Relations' => 'Отношения',
  'Reset' => 'Сброс',
  'Save' => 'Сохранить',
  'Search' => 'Поиск',
  'Update' => 'Обновить',
  'View' => 'Смотреть',
);
