<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Ccbr' => '',
  'Ccbr Branch' => 'Filiāle',
  'Ccbr Branches' => 'FIliāles',
  'Ccbr Ccmp' => 'Uzņēmums',
  'Ccbr Hide' => 'Nerādīt',
  'Ccbr Name' => 'Nosaukums',
  'Ccbr Notes' => 'Piezīmes',
  'CcbrBranch.ccbr_ccmp_id' => 'ID',
  'CcbrBranch.ccbr_hide' => 'Nerādīt',
  'CcbrBranch.ccbr_id' => 'ID',
  'CcbrBranch.ccbr_name' => 'Nosaukums',
  'CcbrBranch.ccbr_notes' => 'Piezīmes',
  'CcbrBranch.ccrb_code' => 'Kods',
  'Ccgr' => 'Grupas',
  'Ccgr Group' => 'Grupa',
  'Ccgr Groups' => 'Grupas',
  'Ccgr Hide' => 'Nerādīt',
  'Ccgr Name' => 'Nosaukums',
  'Ccgr Notes' => 'Piezīmes',
  'CcgrGroup.ccgr_hide' => 'Nerādīt',
  'CcgrGroup.ccgr_id' => 'ID',
  'CcgrGroup.ccgr_name' => 'Nosaukums',
  'CcgrGroup.ccgr_notes' => 'Piezīmes',
  'Ccmp' => 'Uzņēmums',
  'Ccmp Ccnt' => 'Valsts',
  'Ccmp Companies' => 'Uzņemumi',
  'Ccmp Company' => 'Uzņēmums',
  'Ccmp Description' => 'Apraksts',
  'Ccmp Name' => 'Nosaukums',
  'Ccmp Official Address' => 'Fiziskā adrese',
  'Ccmp Registration Address' => 'Juridiskā adrese',
  'Ccmp Registrtion No' => 'Rēģistrācijas numurs',
  'Ccmp Statuss' => 'Statuss',
  'Ccmp Vat Registrtion No' => 'PVN',
  'CcmpCompanies' => 'Uzņēmumi',
  'CcmpCompany.ccmp_ccnt_id' => 'ID',
  'CcmpCompany.ccmp_description' => 'Apraksts',
  'CcmpCompany.ccmp_id' => 'ID',
  'CcmpCompany.ccmp_name' => 'Nosaukums',
  'CcmpCompany.ccmp_official_address' => 'Fiziskā adrese',
  'CcmpCompany.ccmp_registration_address' => 'Juridiskā adrese',
  'CcmpCompany.ccmp_registrtion_no' => 'Reģistrācijas numurs',
  'CcmpCompany.ccmp_statuss' => 'Statuss',
  'CcmpCompany.ccmp_vat_registrtion_no' => 'PVN',
  'Ccnt' => 'Valsts',
  'Ccnt Code' => 'Valsts kods',
  'Ccnt Countries' => 'Valstis',
  'Ccnt Country' => 'Valsts',
  'Ccnt Name' => 'Nosaukums',
  'CcntCountry.ccnt_code' => 'Valsts kods',
  'CcntCountry.ccnt_id' => 'ID',
  'CcntCountry.ccnt_name' => 'Nosaukums',
  'Ccrb Code' => 'Filiāles kods',
  'Ccxg' => '',
  'Ccxg Ccgr' => '',
  'Ccxg Ccmp' => '',
  'Ccxg Company Xgroup' => '',
  'Ccxg Company Xgroups' => '',
  'CcxgCompanyXGroup.ccxg_ccgr_id' => '',
  'CcxgCompanyXGroup.ccxg_ccmp_id' => '',
  'CcxgCompanyXGroup.ccxg_id' => '',
  'CcxgCompanyXGroups' => '',
  'Company branches' => 'Filiāles',
  'Company groups' => 'Grupas',
  'Main comapny data' => 'Pamatdati',
  'Companies' => 'Firmas',
  'Name'  => 'Nosaukums', 
);
